apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels: 
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers: 
      - name: demo-app
        image: us-central1-docker.pkg.dev/citric-shine-378115/demo-app/demo-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100M"
          limits:
            cpu: "250m"
            memory: "500M"
        readinessProbe:
          httpGet:  
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10  # https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-1028654403
          failureThreshold: 2
        livenessProbe:
          httpGet:  
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10  # https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-1028654403
          failureThreshold: 10
