kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: demo-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"   
spec:
  tls:
  - hosts: 
    - app.example.com
    secretName: demo-app-tls
  rules:
  - host: app.example.com 
    http:
      paths:
      - pathType: Prefix
        path: /
        backend: 
          service:
            name: demo-app-service
            port: 
              number: 80
