kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: demo-app-ingress
  annotations:
    # This tells Google Cloud to create an External Load Balancer to realize this Ingress
    kubernetes.io/ingress.class: gce
    # This enables HTTP connections from Internet clients
    kubernetes.io/ingress.allow-http: "true"
spec:
  # tls:
  # - hosts: 
  #   - app.example.com
  #   secretName: demo-app-tls
  rules:
  - host: app.example.com 
    http:
      paths:
      - pathType: Prefix
        path: /
        backend: 
          service:
            name: demo-app-service
            port: 
              number: 80
