kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: demo-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend: 
          serviceName: demo-app-service
          servicePort: 80
