kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: demo-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-staging"
    # nginx.ingress.kubernetes.io/rewrite-target: /           # Target URI where the traffic must be redirected
    
spec:
  tls:
  - hosts: 
    - app.example.com
    secretName: demo-app-tls
  rules:
  - host: app.example.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: demo-app-service
            port: 
              number: 80
